# Generated by Django 4.1.1 on 2022-12-07 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('noOfPlayers', models.PositiveSmallIntegerField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=10)),
                ('hasActor', models.BooleanField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=256)),
                ('scenario', models.TextField(blank=True)),
                ('noOfRiddles', models.PositiveSmallIntegerField(blank=True)),
                ('riddles', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
