# Generated by Django 4.1.1 on 2023-01-11 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('user', 'title')},
        ),
        migrations.RemoveField(
            model_name='room',
            name='noOfRiddles',
        ),
    ]
