# Generated by Django 4.1.1 on 2023-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_riddle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='riddles',
        ),
    ]
